pull_request_rules:
  - name: Automatic merge on label
    conditions:
      - author=kamilbakierzynski
      - base=master
      - label=ready to merge
    actions:
      merge:
        method: merge